
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Character.Entity
{
public partial class CharacterPropertyE
{
    private readonly System.Collections.Generic.Dictionary<int, Character.Unit.CharacterPropertyU> _dataMap;
    private readonly System.Collections.Generic.List<Character.Unit.CharacterPropertyU> _dataList;
    
    public CharacterPropertyE(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.Unit.CharacterPropertyU>();
        _dataList = new System.Collections.Generic.List<Character.Unit.CharacterPropertyU>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Character.Unit.CharacterPropertyU _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Character.Unit.CharacterPropertyU.DeserializeCharacterPropertyU(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.Unit.CharacterPropertyU> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.Unit.CharacterPropertyU> DataList => _dataList;

    public Character.Unit.CharacterPropertyU GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Character.Unit.CharacterPropertyU Get(int key) => _dataMap[key];
    public Character.Unit.CharacterPropertyU this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
