
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Character.Unit
{
public sealed partial class CharacterPropertyU : Luban.BeanBase
{
    public CharacterPropertyU(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["health"].IsNumber) { throw new SerializationException(); }  Health = _buf["health"]; }
        { if(!_buf["default_sprint_speed"].IsNumber) { throw new SerializationException(); }  DefaultSprintSpeed = _buf["default_sprint_speed"]; }
        { if(!_buf["default_running_speed"].IsNumber) { throw new SerializationException(); }  DefaultRunningSpeed = _buf["default_running_speed"]; }
        { if(!_buf["default_walking_speed"].IsNumber) { throw new SerializationException(); }  DefaultWalkingSpeed = _buf["default_walking_speed"]; }
        { if(!_buf["default_aiming_moving_speed"].IsNumber) { throw new SerializationException(); }  DefaultAimingMovingSpeed = _buf["default_aiming_moving_speed"]; }
        { if(!_buf["default_jump_force"].IsNumber) { throw new SerializationException(); }  DefaultJumpForce = _buf["default_jump_force"]; }
    }

    public static CharacterPropertyU DeserializeCharacterPropertyU(JSONNode _buf)
    {
        return new Character.Unit.CharacterPropertyU(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 血量上限
    /// </summary>
    public readonly int Health;
    /// <summary>
    /// 默认最大冲刺速度
    /// </summary>
    public readonly float DefaultSprintSpeed;
    /// <summary>
    /// 默认最大奔跑速度
    /// </summary>
    public readonly float DefaultRunningSpeed;
    /// <summary>
    /// 默认最大行走速度
    /// </summary>
    public readonly float DefaultWalkingSpeed;
    /// <summary>
    /// 默认瞄准时移动速度
    /// </summary>
    public readonly float DefaultAimingMovingSpeed;
    /// <summary>
    /// 默认跳跃能力
    /// </summary>
    public readonly float DefaultJumpForce;
   
    public const int __ID__ = 1993486524;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "health:" + Health + ","
        + "defaultSprintSpeed:" + DefaultSprintSpeed + ","
        + "defaultRunningSpeed:" + DefaultRunningSpeed + ","
        + "defaultWalkingSpeed:" + DefaultWalkingSpeed + ","
        + "defaultAimingMovingSpeed:" + DefaultAimingMovingSpeed + ","
        + "defaultJumpForce:" + DefaultJumpForce + ","
        + "}";
    }
}

}
