
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Scene.Entity
{
public partial class SceneAdditiveDataE
{
    private readonly System.Collections.Generic.Dictionary<int, Scene.Unit.SceneAdditiveDataU> _dataMap;
    private readonly System.Collections.Generic.List<Scene.Unit.SceneAdditiveDataU> _dataList;
    
    public SceneAdditiveDataE(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Scene.Unit.SceneAdditiveDataU>();
        _dataList = new System.Collections.Generic.List<Scene.Unit.SceneAdditiveDataU>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Scene.Unit.SceneAdditiveDataU _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Scene.Unit.SceneAdditiveDataU.DeserializeSceneAdditiveDataU(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Scene.Unit.SceneAdditiveDataU> DataMap => _dataMap;
    public System.Collections.Generic.List<Scene.Unit.SceneAdditiveDataU> DataList => _dataList;

    public Scene.Unit.SceneAdditiveDataU GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Scene.Unit.SceneAdditiveDataU Get(int key) => _dataMap[key];
    public Scene.Unit.SceneAdditiveDataU this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
