
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Scene.Unit
{
public sealed partial class SceneAdditiveDataU : Luban.BeanBase
{
    public SceneAdditiveDataU(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["SceneName"].IsString) { throw new SerializationException(); }  SceneName = _buf["SceneName"]; }
        { if(!_buf["ScenePathPrefix"].IsString) { throw new SerializationException(); }  ScenePathPrefix = _buf["ScenePathPrefix"]; }
        { if(!_buf["SceneFullPath"].IsString) { throw new SerializationException(); }  SceneFullPath = _buf["SceneFullPath"]; }
        { if(!_buf["BuildIndex"].IsNumber) { throw new SerializationException(); }  BuildIndex = _buf["BuildIndex"]; }
        { if(!_buf["targetSceneHandler"].IsString) { throw new SerializationException(); }  TargetSceneHandler = _buf["targetSceneHandler"]; }
    }

    public static SceneAdditiveDataU DeserializeSceneAdditiveDataU(JSONNode _buf)
    {
        return new Scene.Unit.SceneAdditiveDataU(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// SceneName
    /// </summary>
    public readonly string SceneName;
    /// <summary>
    /// the prefix of path
    /// </summary>
    public readonly string ScenePathPrefix;
    /// <summary>
    /// full path in asset
    /// </summary>
    public readonly string SceneFullPath;
    /// <summary>
    /// build index in &#39;build settings&#39;
    /// </summary>
    public readonly int BuildIndex;
    /// <summary>
    /// target scene handler which inherit UIHandler
    /// </summary>
    public readonly string TargetSceneHandler;
   
    public const int __ID__ = 1329641851;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "SceneName:" + SceneName + ","
        + "ScenePathPrefix:" + ScenePathPrefix + ","
        + "SceneFullPath:" + SceneFullPath + ","
        + "BuildIndex:" + BuildIndex + ","
        + "targetSceneHandler:" + TargetSceneHandler + ","
        + "}";
    }
}

}
