
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Character.Entity.CharacterPropertyE CharacterPropertyE {get; }
    public Scene.Entity.SceneAdditiveDataE SceneAdditiveDataE {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        CharacterPropertyE = new Character.Entity.CharacterPropertyE(loader("character_entity_characterpropertye"));
        SceneAdditiveDataE = new Scene.Entity.SceneAdditiveDataE(loader("scene_entity_sceneadditivedatae"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        CharacterPropertyE.ResolveRef(this);
        SceneAdditiveDataE.ResolveRef(this);
    }
}

}
